### ISSUE TITLE
打包web加载报错

### ISSUE THREAD

**Issue by kyo8598CC** [NoRainLand/WheelChairMan#1]
![image](https://github.com/NoRainLand/WheelChairMan/assets/129036439/50a6e3a7-94b4-46e9-90ce-c71e4ed7c710)
大佬 打包web出来会出现加载错误 然后运行不下去

**Comment by NoRainLand** [comment]
不确定什么问题，我更新了一版本，你可以重新同步一下看看，里边有我打包好的web
